# Generated by Django 4.2.17 on 2025-12-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код объекта"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Бизнес-объект",
                "verbose_name_plural": "Бизнес-объекты",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название роли"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccessRoleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_permission",
                    models.BooleanField(default=False, verbose_name="Чтение своих"),
                ),
                (
                    "create_permission",
                    models.BooleanField(default=False, verbose_name="Создание своих"),
                ),
                (
                    "update_permission",
                    models.BooleanField(default=False, verbose_name="Обновление своих"),
                ),
                (
                    "delete_permission",
                    models.BooleanField(default=False, verbose_name="Удаление своих"),
                ),
                (
                    "read_all_permission",
                    models.BooleanField(default=False, verbose_name="Чтение всех"),
                ),
                (
                    "update_all_permission",
                    models.BooleanField(default=False, verbose_name="Обновление всех"),
                ),
                (
                    "delete_all_permission",
                    models.BooleanField(default=False, verbose_name="Удаление всех"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="authorization.businesselement",
                        verbose_name="Бизнес-объект",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="authorization.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа",
                "verbose_name_plural": "Правила доступа",
                "ordering": ["role", "element"],
                "unique_together": {("role", "element")},
            },
        ),
    ]
